In [1]:
import pandas as pd

/tmp/ipykernel_1012069/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was too old on your system - pyarrow 10.0.1 is the current minimum supported version as of this release.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

#### 2023 data

In [2]:
event_2023 = pd.read_csv("event_data_2023.csv")

In [3]:
event_2023

,id,player_id,team_id,minute,second,period,start_x,start_y,end_x,end_y,...,possession_counterattack,possession_direct_free_kick,possession_penalty,match_time,approx_match_time,season,match_id,competition,start_frame,frame
0,1720110143,899799,6766,0,7,1,30.870,23.5824,85.491276,41.517396,...,False,False,False,7,3.749232e+03,2023,5420815,808,93.73081,94.0
1,1720110210,678625,6766,1,5,1,90.405,34.2176,100.114784,32.081624,...,False,False,False,65,6.140123e+04,2023,5420815,808,1535.03080,1535.0
2,1720109864,169221,6736,2,16,1,81.585,38.3792,85.491276,33.496990,...,False,False,False,136,1.325612e+05,2023,5420815,808,3314.03080,3314.0
3,1720109865,676584,6736,2,16,1,83.790,32.8304,89.990817,31.609836,...,False,False,False,136,1.326092e+05,2023,5420815,808,3315.23100,3315.0
4,1720109866,553319,6736,2,18,1,88.200,30.9808,88.865932,18.871544,...,False,False,False,138,1.343772e+05,2023,5420815,808,3359.43100,3359.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31763,1625749288,212662,6721,91,56,2,88.200,24.9696,92.240588,33.968779,...,False,False,False,5516,2.815951e+06,2023,5420697,808,70398.78000,70399.0
31764,1625749300,587166,6721,92,53,2,63.945,4.1616,87.741047,8.020406,...,True,False,False,5573,2.873558e+06,2023,5420697,808,71838.95000,71839.0
31765,1625749310,676013,6721,94,9,2,105.000,4.1616,105.000000,13.681869,...,False,False,False,5649,2.949068e+06,2023,5420697,808,73726.70000,73727.0
31766,1625748978,581623,6754,95,22,2,72.765,20.3456,105.000000,4.717886,...,False,False,False,5722,3.022730e+06,2023,5420697,808,75568.26000,75568.0
31767,1625748995,578850,6754,96,23,2,22.050,30.5184,82.116621,8.963983,...,False,False,False,5783,3.083156e+06,2023,5420697,808,77078.91000,77079.0

In [4]:
event_features_2023 = pd.read_csv("event_features_2023.csv")

In [5]:
event_features_2023["actual_xG"] = event_2023["possession_xg"]

In [6]:
event_features_2023['possession_goal'] = event_2023['possession_goal']

In [7]:
event_features_2023 = event_features_2023.rename(columns={"passer distance goal": "start_distance_to_goal",
    "pass end distance to goal" : "end_distance_to_goal",
    "pass length": "pass_length",
    "pass angle": "pass_angle",
    "passer angle goal": "start_angle_to_goal",
    "pass end angle to goal": "end_angle_to_goal",
    "Passer distance to sideline": "start_distance_to_sideline",
    "pass end distance to sideline": "end_distance_to_sideline", 
    "opponents behind passer": "opponents_behind",
    "teammates behind passer": "teammates_behind",
    "total pressure passer": "pressure_on_passer",
    "teammates beyond passer": "teammates_beyond",
    "opponents beyond passer": "opponents_beyond",
    "opponents between": "Opponents_between",
    "opponents bypass new": "packing",
    "opponents near the passer": "opponents_nearby",
    "average speed team": "average_speed_of_teammates",
    "average speed opponent": "average_speed_of_opponents",
    "teammates near passer": "teammates_nearby"})

In [8]:
event_features_2023.columns

Index(['id', 'player_id', 'match_id', 'team_id', 'possession_team_id',
       'start_x', 'start_y', 'end_x', 'end_y', 'passer_x', 'passer_y',
       'possession_xG_target', 'start_distance_to_goal',
       'end_distance_to_goal', 'pass_length', 'pass_angle',
       'start_angle_to_goal', 'end_angle_to_goal',
       'start_distance_to_sideline', 'end_distance_to_sideline',
       'forward pass', 'backward pass', 'lateral pass', 'teammates_behind',
       'teammates_beyond', 'opponents_beyond', 'opponents_behind',
       'opponents_between', 'packing', 'pressure_on_passer',
       'opponents_nearby', 'pressure level passer',
       'average_speed_of_teammates', 'average_speed_of_opponents',
       'teammates_nearby', 'pass_recipient_id', 'actual_xG',
       'possession_goal'],
      dtype='object')

In [9]:
tracking_2023 = pd.read_csv("tracking_data_2023.csv")

In [10]:
tracking_2023

,team_id,team,jersey_number,player,role,speed,x_signality,y_signality,vx_signality,vy_signality,...,frame,minute,second,period,start_frame,player_id_event,possession_team_id,player_count,player_name,player_id
0,6736,home_team,19,Srdjan Hrstic,10,5.346,-20.74,-0.79,0,0,...,786,45,34,2,786.427124,252473,6736,22,srdjan hrstic,676584
1,6736,home_team,11,Samuel Gustafson,7,2.977,-2.89,-8.91,0,0,...,786,45,34,2,786.427124,252473,6736,22,samuel gustafson,252473
2,6736,home_team,8,Abdulrazaq Ishaq,6,4.319,-11.31,-22.52,0,0,...,786,45,34,2,786.427124,252473,6736,22,abdulrazaq ishaq,553319
3,6736,home_team,27,Akoua Romeo Amane,8,0.347,-8.75,8.78,0,0,...,786,45,34,2,786.427124,252473,6736,22,akoua amane,806885
4,6736,home_team,5,Even Hovland,4,1.706,10.41,11.74,0,0,...,786,45,34,2,786.427124,252473,6736,22,even hovland,54538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694275,6721,away_team,23,Niklas Hult,5,4.066,6.62,21.02,0,0,...,77079,96,23,2,77078.906250,578850,6754,22,niklas hult,51146
694276,6721,away_team,30,Hákon Valdimarsson,1,0.875,38.77,1.57,0,0,...,77079,96,23,2,77078.906250,578850,6754,22,hakon valdimarsson,504579
694277,6721,away_team,18,Ahmed Qasem,0,3.000,-6.60,-15.14,0,0,...,77079,96,23,2,77078.906250,578850,6754,22,ahmed qasem,676013
694278,6721,away_team,29,Buhari Ibrahim,0,0.939,-11.60,-8.06,0,0,...,77079,96,23,2,77078.906250,578850,6754,22,buhari ibrahim,831111
694279,6721,away_team,25,Jack Cooper-Love,0,3.314,9.14,-1.26,0,0,...,77079,96,23,2,77078.906250,578850,6754,22,jack cooper-love,587166

In [11]:
tracking_2023.columns

Index(['team_id', 'team', 'jersey_number', 'player', 'role', 'speed',
       'x_signality', 'y_signality', 'vx_signality', 'vy_signality',
       'x_adjusted', 'y_adjusted', 'pitch_length', 'pitch_width',
       'team_direction', 'id', 'frame', 'minute', 'second', 'period',
       'start_frame', 'player_id_event', 'possession_team_id', 'player_count',
       'player_name', 'player_id'],
      dtype='object')

In [12]:
#Get passer name mapping
passer_rows = tracking_2023.merge(event_features_2023, on=['id', 'player_id'], how='inner')
passer_names = passer_rows[['id', 'player_id', 'player_name']].drop_duplicates()

#Merge passer name
event_with_passer = event_features_2023.merge(
    passer_names,
    on=['id', 'player_id'],
    how='left'
).rename(columns={'player_name': 'passer_name'})

# Get receiver name mapping
receiver_lookup = tracking_2023.merge(
    event_features_2023[['id', 'pass_recipient_id']].drop_duplicates(),
    left_on=['id', 'player_id'],
    right_on=['id', 'pass_recipient_id'],
    how='inner'
)
receiver_names = receiver_lookup[['id', 'player_id', 'player_name']].drop_duplicates()

# Merge receiver name into the result that already has passer_name
event_features_2023_final = event_with_passer.merge(
    receiver_names,
    left_on=['id', 'pass_recipient_id'],
    right_on=['id', 'player_id'],
    how='left'
).rename(columns={'player_name': 'receiver_name'}).drop(columns=['player_id'], errors='ignore')

In [13]:
event_features_2023_final.columns

Index(['id', 'player_id_x', 'match_id', 'team_id', 'possession_team_id',
       'start_x', 'start_y', 'end_x', 'end_y', 'passer_x', 'passer_y',
       'possession_xG_target', 'start_distance_to_goal',
       'end_distance_to_goal', 'pass_length', 'pass_angle',
       'start_angle_to_goal', 'end_angle_to_goal',
       'start_distance_to_sideline', 'end_distance_to_sideline',
       'forward pass', 'backward pass', 'lateral pass', 'teammates_behind',
       'teammates_beyond', 'opponents_beyond', 'opponents_behind',
       'opponents_between', 'packing', 'pressure_on_passer',
       'opponents_nearby', 'pressure level passer',
       'average_speed_of_teammates', 'average_speed_of_opponents',
       'teammates_nearby', 'pass_recipient_id', 'actual_xG', 'possession_goal',
       'passer_name', 'player_id_y', 'receiver_name'],
      dtype='object')

In [14]:
event_features_2023_final.drop(['player_id_y'],axis=1,inplace=True)

In [15]:
event_features_2023_final = event_features_2023_final.rename(columns={'player_id_x' : 'player_id'})

In [16]:
event_features_2023_final.columns

Index(['id', 'player_id', 'match_id', 'team_id', 'possession_team_id',
       'start_x', 'start_y', 'end_x', 'end_y', 'passer_x', 'passer_y',
       'possession_xG_target', 'start_distance_to_goal',
       'end_distance_to_goal', 'pass_length', 'pass_angle',
       'start_angle_to_goal', 'end_angle_to_goal',
       'start_distance_to_sideline', 'end_distance_to_sideline',
       'forward pass', 'backward pass', 'lateral pass', 'teammates_behind',
       'teammates_beyond', 'opponents_beyond', 'opponents_behind',
       'opponents_between', 'packing', 'pressure_on_passer',
       'opponents_nearby', 'pressure level passer',
       'average_speed_of_teammates', 'average_speed_of_opponents',
       'teammates_nearby', 'pass_recipient_id', 'actual_xG', 'possession_goal',
       'passer_name', 'receiver_name'],
      dtype='object')

In [17]:
event_features_2023_final

,id,player_id,match_id,team_id,possession_team_id,start_x,start_y,end_x,end_y,passer_x,...,opponents_nearby,pressure level passer,average_speed_of_teammates,average_speed_of_opponents,teammates_nearby,pass_recipient_id,actual_xG,possession_goal,passer_name,receiver_name
0,1720110143,899799,5420815,6766,6736,29.40,34.68,80.606061,60.444444,29.743581,...,0,Low Pressure,2.871000,1.968636,0,569305,0.0000,False,malcolm jeng,jakob persson
1,1720110210,678625,5420815,6766,6736,86.10,50.32,94.393939,46.707071,84.794345,...,3,Middle Pressure,2.751364,1.949273,0,640395,0.0671,True,melker heier,joakim persson
2,1720109864,169221,5420815,6736,6736,77.70,56.44,80.606061,48.767677,72.362573,...,1,Low Pressure,4.344273,4.469273,0,676584,0.0000,False,simon sandberg,srdjan hrstic
3,1720109865,676584,5420815,6736,6736,79.80,48.28,84.848485,46.020202,75.507486,...,2,Low Pressure,4.303182,4.442636,0,553319,0.0000,False,srdjan hrstic,abdulrazaq ishaq
4,1720109866,553319,5420815,6736,6736,84.00,45.56,83.787879,27.474747,84.656324,...,3,Middle Pressure,3.047545,3.189909,1,53649,0.0000,False,abdulrazaq ishaq,amor layouni
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31763,1625749288,212662,5420697,6721,6736,84.00,36.72,86.969697,49.454545,82.423686,...,3,Middle Pressure,2.924000,2.798182,0,509754,0.0209,False,andre romer,michael baidoo
31764,1625749300,587166,5420697,6721,6736,60.90,6.12,82.727273,11.676768,55.896746,...,0,Low Pressure,3.270364,2.900100,1,607268,0.0000,False,jack cooper-love,jacob ondrejka
31765,1625749310,676013,5420697,6721,6736,103.95,6.12,101.818182,19.919192,103.643298,...,1,Low Pressure,0.945455,0.732000,1,587166,0.0000,False,ahmed qasem,jack cooper-love
31766,1625748978,581623,5420697,6754,6736,69.30,29.92,101.818182,6.868687,80.958592,...,2,Low Pressure,1.761818,2.840100,2,730438,0.0000,False,herman johansson,otto rosengren
31767,1625748995,578850,5420697,6754,6736,21.00,44.88,77.424242,13.050505,24.178908,...,0,Low Pressure,2.884455,2.547182,0,338960,0.0000,False,noah eile,mamudu moro

In [18]:
team_2023 = pd.read_csv("team_ids_2023.csv")

In [19]:
team_2023

         team_name  team_id
0            Malmö     6709
1      IF Elfsborg     6721
2           Häcken     6736
3       Djurgården     6713
4          Värnamo     6769
5           Kalmar     6711
6         Hammarby     6710
7           Sirius     6766
8       Norrköping     6726
9          Mjällby     6754
10             AIK     6716
11    Halmstads BK     6708
12        Göteborg     6712
13  Brommapojkarna     6725
14       Degerfors     6741
15         Varberg     6897

In [20]:
event_features_2023_final = event_features_2023_final.merge(
    team_2023[['team_id', 'team_name']],
    on='team_id',
    how='left'  # keeps all events even if no matching team found
)

In [48]:
event_features_2023_final = event_features_2023_final[['id', 'match_id', 'team_id', 'possession_team_id', 'player_id', 'passer_name', 'pass_recipient_id',
       'receiver_name', 'team_name','start_x', 'start_y', 'end_x', 'end_y', 'passer_x', 'passer_y',
       'start_distance_to_goal','end_distance_to_goal', 'pass_length', 'pass_angle','start_angle_to_goal', 'end_angle_to_goal','start_distance_to_sideline', 'end_distance_to_sideline',
       'forward pass', 'backward pass', 'lateral pass', 'teammates_behind','teammates_beyond', 'opponents_beyond', 'opponents_behind',
       'opponents_between', 'packing', 'pressure_on_passer','average_speed_of_teammates', 'average_speed_of_opponents','opponents_nearby','pressure level passer',
       'teammates_nearby', 'actual_xG', 'possession_goal','possession_xG_target'
       ]]

In [49]:
event_features_2023_final

,id,match_id,team_id,possession_team_id,player_id,passer_name,pass_recipient_id,receiver_name,team_name,start_x,...,packing,pressure_on_passer,average_speed_of_teammates,average_speed_of_opponents,opponents_nearby,pressure level passer,teammates_nearby,actual_xG,possession_goal,possession_xG_target
0,1720110143,5420815,6766,6736,899799,malcolm jeng,569305,jakob persson,Sirius,29.40,...,2,0.000000,2.871000,1.968636,0,Low Pressure,0,0.0000,False,0
1,1720110210,5420815,6766,6736,678625,melker heier,640395,joakim persson,Sirius,86.10,...,5,1.330670,2.751364,1.949273,3,Middle Pressure,0,0.0671,True,1
2,1720109864,5420815,6736,6736,169221,simon sandberg,676584,srdjan hrstic,Häcken,77.70,...,4,0.568734,4.344273,4.469273,1,Low Pressure,0,0.0000,False,0
3,1720109865,5420815,6736,6736,676584,srdjan hrstic,553319,abdulrazaq ishaq,Häcken,79.80,...,2,0.188626,4.303182,4.442636,2,Low Pressure,0,0.0000,False,0
4,1720109866,5420815,6736,6736,553319,abdulrazaq ishaq,53649,amor layouni,Häcken,84.00,...,2,1.421722,3.047545,3.189909,3,Middle Pressure,1,0.0000,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31763,1625749288,5420697,6721,6736,212662,andre romer,509754,michael baidoo,IF Elfsborg,84.00,...,4,1.111481,2.924000,2.798182,3,Middle Pressure,0,0.0209,False,0
31764,1625749300,5420697,6721,6736,587166,jack cooper-love,607268,jacob ondrejka,IF Elfsborg,60.90,...,3,0.000000,3.270364,2.900100,0,Low Pressure,1,0.0000,False,0
31765,1625749310,5420697,6721,6736,676013,ahmed qasem,587166,jack cooper-love,IF Elfsborg,103.95,...,4,0.851574,0.945455,0.732000,1,Low Pressure,1,0.0000,False,0
31766,1625748978,5420697,6754,6736,581623,herman johansson,730438,otto rosengren,Mjällby,69.30,...,2,1.174059,1.761818,2.840100,2,Low Pressure,2,0.0000,False,0
31767,1625748995,5420697,6754,6736,578850,noah eile,338960,mamudu moro,Mjällby,21.00,...,3,0.000000,2.884455,2.547182,0,Low Pressure,0,0.0000,False,0

### 2022 data

In [24]:
event_2022 = pd.read_csv("event_data_2022.csv")
tracking_2022 = pd.read_csv("tracking_data_2022.csv")

In [25]:
event_features_2022 = pd.read_csv("event_features_2022.csv")

In [26]:
team_2022 = pd.read_csv("team_ids_2022.csv")

In [27]:
event_features_2022["actual_xG"] = event_2022["possession_xg"]
event_features_2022['possession_goal'] = event_2022['possession_goal']

In [28]:
event_features_2022 = event_features_2022.rename(columns={"passer distance goal": "start_distance_to_goal",
    "pass end distance to goal" : "end_distance_to_goal",
    "pass length": "pass_length",
    "pass angle": "pass_angle",
    "passer angle goal": "start_angle_to_goal",
    "pass end angle to goal": "end_angle_to_goal",
    "Passer distance to sideline": "start_distance_to_sideline",
    "pass end distance to sideline": "end_distance_to_sideline", 
    "opponents behind passer": "opponents_behind",
    "teammates behind passer": "teammates_behind",
    "total pressure passer": "pressure_on_passer",
    "teammates beyond passer": "teammates_beyond",
    "opponents beyond passer": "opponents_beyond",
    "opponents between": "Opponents_between",
    "opponents bypass new": "packing",
    "opponents near the passer": "opponents_nearby",
    "average speed team": "average_speed_of_teammates",
    "average speed opponent": "average_speed_of_opponents",
    "teammates near passer": "teammates_nearby"})

In [29]:
#Get passer name mapping
passer_rows_2022 = tracking_2022.merge(event_features_2022, on=['id', 'player_id'], how='inner')
passer_names_2022 = passer_rows_2022[['id', 'player_id', 'player_name']].drop_duplicates()

#Merge passer name
event_with_passer_2022 = event_features_2022.merge(
    passer_names_2022,
    on=['id', 'player_id'],
    how='left'
).rename(columns={'player_name': 'passer_name'})

# Get receiver name mapping
receiver_lookup_2022 = tracking_2022.merge(
    event_features_2022[['id', 'pass_recipient_id']].drop_duplicates(),
    left_on=['id', 'player_id'],
    right_on=['id', 'pass_recipient_id'],
    how='inner'
)
receiver_names_2022 = receiver_lookup_2022[['id', 'player_id', 'player_name']].drop_duplicates()

# Merge receiver name into the result that already has passer_name
event_features_2022_final = event_with_passer_2022.merge(
    receiver_names_2022,
    left_on=['id', 'pass_recipient_id'],
    right_on=['id', 'player_id'],
    how='left'
).rename(columns={'player_name': 'receiver_name'}).drop(columns=['player_id'], errors='ignore')

In [30]:
event_features_2022_final.columns

Index(['id', 'player_id_x', 'match_id', 'team_id', 'possession_team_id',
       'passer_x', 'passer_y', 'start_x', 'start_y', 'end_x', 'end_y',
       'possession_xG_target', 'start_distance_to_goal',
       'end_distance_to_goal', 'pass_length', 'pass_angle',
       'start_angle_to_goal', 'end_angle_to_goal',
       'start_distance_to_sideline', 'end_distance_to_sideline',
       'forward pass', 'backward pass', 'lateral pass', 'teammates_behind',
       'teammates_beyond', 'opponents_beyond', 'opponents_behind',
       'opponents_between', 'packing', 'pressure_on_passer',
       'pressure level passer', 'average_speed_of_teammates',
       'average_speed_of_opponents', 'opponents_nearby', 'teammates_nearby',
       'pass_recipient_id', 'actual_xG', 'possession_goal', 'passer_name',
       'player_id_y', 'receiver_name'],
      dtype='object')

In [31]:
event_features_2022_final.drop(['player_id_y'],axis=1,inplace=True)
event_features_2022_final = event_features_2022_final.rename(columns={'player_id_x' : 'player_id'})

In [32]:
event_features_2022_final = event_features_2022_final.merge(
    team_2022[['team_id', 'team_name']],
    on='team_id',
    how='left'  # keeps all events even if no matching team found
)

In [33]:
event_features_2023_final.columns

Index(['id', 'match_id', 'team_id', 'possession_team_id', 'player_id',
       'passer_name', 'pass_recipient_id', 'receiver_name', 'team_name',
       'start_x', 'start_y', 'end_x', 'end_y', 'passer_x', 'passer_y',
       'start_distance_to_goal', 'end_distance_to_goal', 'pass_length',
       'pass_angle', 'start_angle_to_goal', 'end_angle_to_goal',
       'start_distance_to_sideline', 'end_distance_to_sideline',
       'forward pass', 'backward pass', 'lateral pass', 'teammates_behind',
       'teammates_beyond', 'opponents_beyond', 'opponents_behind',
       'opponents_between', 'packing', 'pressure_on_passer',
       'opponents_nearby', 'pressure level passer',
       'average_speed_of_teammates', 'average_speed_of_opponents',
       'teammates_nearby', 'actual_xG', 'possession_goal',
       'possession_xG_target'],
      dtype='object')

In [50]:
event_features_2022_final = event_features_2022_final[['id', 'match_id', 'team_id', 'possession_team_id', 'player_id', 'passer_name', 'pass_recipient_id',
       'receiver_name', 'team_name','start_x', 'start_y', 'end_x', 'end_y', 'passer_x', 'passer_y',
       'start_distance_to_goal','end_distance_to_goal', 'pass_length', 'pass_angle','start_angle_to_goal', 'end_angle_to_goal','start_distance_to_sideline', 'end_distance_to_sideline',
       'forward pass', 'backward pass', 'lateral pass', 'teammates_behind','teammates_beyond', 'opponents_beyond', 'opponents_behind',
       'opponents_between', 'packing', 'pressure_on_passer','average_speed_of_teammates', 'average_speed_of_opponents','opponents_nearby','pressure level passer',
       'teammates_nearby', 'actual_xG', 'possession_goal','possession_xG_target'
       ]]

In [51]:
event_features_2022_final

,id,match_id,team_id,possession_team_id,player_id,passer_name,pass_recipient_id,receiver_name,team_name,start_x,...,packing,pressure_on_passer,average_speed_of_teammates,average_speed_of_opponents,opponents_nearby,pressure level passer,teammates_nearby,actual_xG,possession_goal,possession_xG_target
0,1256506933,5321419,6769,6769,77272,francis vries,487935,wenderson nascimento,Värnamo,54.60,...,2,0.000000,2.548364,3.055364,0,Low Pressure,0,0.0,False,0
1,1256508233,5321419,6766,6769,546328,laorent shabani,272752,aron bjarnason,Sirius,72.45,...,1,0.777216,2.347700,2.346909,1,Low Pressure,0,0.0,False,0
2,1256507062,5321419,6769,6769,654790,robin tihi,582334,victor larsson,Värnamo,61.95,...,1,0.483192,3.192000,2.942000,1,Low Pressure,0,0.0,False,0
3,1256507101,5321419,6769,6769,654790,robin tihi,77272,francis vries,Värnamo,88.20,...,1,0.193301,2.076364,2.067000,1,Low Pressure,0,0.0,False,0
4,1256507134,5321419,6769,6769,582334,victor larsson,259306,evaldo neto,Värnamo,72.45,...,3,0.080622,1.566364,1.748000,1,Low Pressure,0,0.0,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42314,1368462109,5321563,6709,6736,347591,felix beijmo,258141,erdal rakip,Malmö,69.30,...,1,0.522801,2.005182,0.989273,1,Low Pressure,0,0.0,False,0
42315,1368462114,5321563,6709,6736,54544,jo berget,418949,veljko birmancevic,Malmö,47.25,...,4,0.402356,3.295909,3.906909,1,Low Pressure,0,0.0,False,0
42316,1368462115,5321563,6709,6736,418949,veljko birmancevic,56259,anders christiansen,Malmö,84.00,...,0,0.650397,4.139455,5.203091,1,Low Pressure,0,0.0,False,0
42317,1368462127,5321563,6709,6736,56259,anders christiansen,347591,felix beijmo,Malmö,58.80,...,2,0.310030,1.130273,1.688818,1,Low Pressure,0,0.0,False,0
42318,1368462129,5321563,6709,6736,347591,felix beijmo,56259,anders christiansen,Malmö,76.65,...,4,0.436715,3.576182,3.973818,2,Low Pressure,0,0.0,False,0

In [36]:
event_features_2022_final.columns

Index(['id', 'match_id', 'team_id', 'possession_team_id', 'player_id',
       'passer_name', 'pass_recipient_id', 'receiver_name', 'team_name',
       'start_x', 'start_y', 'end_x', 'end_y', 'passer_x', 'passer_y',
       'start_distance_to_goal', 'end_distance_to_goal', 'pass_length',
       'pass_angle', 'start_angle_to_goal', 'end_angle_to_goal',
       'start_distance_to_sideline', 'end_distance_to_sideline',
       'forward pass', 'backward pass', 'lateral pass', 'teammates_behind',
       'teammates_beyond', 'opponents_beyond', 'opponents_behind',
       'opponents_between', 'packing', 'pressure_on_passer',
       'opponents_nearby', 'pressure level passer',
       'average_speed_of_teammates', 'average_speed_of_opponents',
       'teammates_nearby', 'actual_xG', 'possession_goal',
       'possession_xG_target'],
      dtype='object')

In [52]:
# For 2022 tracking data
event_features_2022_final['season'] = '2022'

# For 2023 tracking data
event_features_2023_final['season'] = '2023'

# Concatenate both
features_2022_2023_final = pd.concat([event_features_2022_final, event_features_2023_final], ignore_index=True)

###feature for Logistic

In [53]:
features_2022_2023_final["speed_difference"] = features_2022_2023_final["average_speed_of_teammates"] - features_2022_2023_final["average_speed_of_opponents"]

In [54]:
features_2022_2023_final.to_csv("features_2022_2023_final.csv",index=False)

In [46]:
features_2022_2023_final.columns

Index(['id', 'match_id', 'team_id', 'possession_team_id', 'player_id',
       'passer_name', 'pass_recipient_id', 'receiver_name', 'team_name',
       'start_x', 'start_y', 'end_x', 'end_y', 'passer_x', 'passer_y',
       'start_distance_to_goal', 'end_distance_to_goal', 'pass_length',
       'pass_angle', 'start_angle_to_goal', 'end_angle_to_goal',
       'start_distance_to_sideline', 'end_distance_to_sideline',
       'forward pass', 'backward pass', 'lateral pass', 'teammates_behind',
       'teammates_beyond', 'opponents_beyond', 'opponents_behind',
       'opponents_between', 'packing', 'pressure_on_passer',
       'opponents_nearby', 'pressure level passer',
       'average_speed_of_teammates', 'average_speed_of_opponents',
       'teammates_nearby', 'actual_xG', 'possession_goal',
       'possession_xG_target', 'season', 'speed_difference'],
      dtype='object')

In [40]:
event_features_2022.to_csv("event_features_2022.csv",index=False)
event_features_2023.to_csv("event_features_2023.csv",index=False)

In [41]:
tracking_2022_2023 = pd.read_parquet("tracking_2022_2023.parquet")

In [42]:
tracking_2022_2023

,id,team_id,team,possession_team_id,x_adjusted,y_adjusted,team_direction,player_name,player_id,pitch_length,pitch_width,match_id,season
0,1256506933,6769,home_team,6769,59.709257,43.138138,left,abdussalam magashy,570514,103,66,5321419,2022
1,1256506933,6769,home_team,6769,85.225169,35.061862,left,oscar johansson,258122,103,66,5321419,2022
2,1256506933,6769,home_team,6769,61.126808,28.639640,left,william kenndal,252439,103,66,5321419,2022
3,1256506933,6769,home_team,6769,78.917068,43.413814,left,marcus antonsson,50789,103,66,5321419,2022
4,1256506933,6769,home_team,6769,46.465284,42.239640,left,victor eriksson,570392,103,66,5321419,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619703,1625748995,6721,away_team,6754,45.679896,54.947804,left,niklas hult,51146,107,65,5420697,2023
1619704,1625748995,6721,away_team,6754,14.485999,35.108658,left,hakon valdimarsson,504579,107,65,5420697,2023
1619705,1625748995,6721,away_team,6754,58.506748,18.064333,left,ahmed qasem,676013,107,65,5420697,2023
1619706,1625748995,6721,away_team,6754,63.358054,25.285986,left,buhari ibrahim,831111,107,65,5420697,2023
1619707,1625748995,6721,away_team,6754,43.234838,32.222037,left,jack cooper-love,587166,107,65,5420697,2023